#!/bin/bash

mkdir ~/configImage_temp
cd ~/configImage_temp

# Installing Chrome
curl -L -O "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg"
hdiutil mount -nobrowse googlechrome.dmg
cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
hdiutil unmount "/Volumes/Google Chrome"
rm googlechrome.dmg

# Installing Firefox
curl -L -o Firefox.dmg "http://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US"
hdiutil mount -nobrowse Firefox.dmg
cp -R "/Volumes/Firefox/Firefox.app" /Applications
hdiutil unmount "/Volumes/Firefox"
rm Firefox.dmg

# Installing VLC Player
curl -L -o vlc.dmg "http://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg"
hdiutil mount -nobrowse vlc.dmg -mountpoint /Volumes/vlc
cp -R "/Volumes/vlc/VLC.app" /Applications
hdiutil unmount "/Volumes/vlc"
rm vlc.dmg

# Installing LibreOffice
curl -L -o LibreOffice.dmg "http://download.documentfoundation.org/libreoffice/stable/5.3.2/mac/x86_64/LibreOffice_5.3.2_MacOS_x86-64.dmg" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36"
hdiutil mount -nobrowse LibreOffice.dmg
cp -R "/Volumes/LibreOffice/LibreOffice.app" /Applications
hdiutil unmount "/Volumes/LibreOffice"
rm LibreOffice.dmg

# Installing The Unarchiver
curl -L -o TheUnarchiver.zip "http://unarchiver.c3.cx/downloads/TheUnarchiver3.11.1.zip"
unzip TheUnarchiver.zip
mv "The Unarchiver.app" /Applications
rm TheUnarchiver.zip

